apiRules:
- include:
    uidRegex: ^Symphogear
    type: Namespace
- include:
    uidRegex: ^Symphogear\.Editor
    type: Namespace
- include:
    uidRegex: ^Global
    type: Namespace
- exclude:
    uidRegex: .*
    type: Namespace
